# Generated by Django 3.1.7 on 2021-05-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='first_name',
            field=models.CharField(default='teste', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestor',
            name='last_name',
            field=models.CharField(default='teste', max_length=15),
            preserve_default=False,
        ),
    ]
