# Generated by Django 3.1.7 on 2021-05-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210509_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Já existe um gestor registado com este email!'}, max_length=60, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='username',
            field=models.CharField(error_messages={'unique': 'Já existe um gestor registado com este username!'}, max_length=30, unique=True),
        ),
    ]
