# Generated by Django 3.1.7 on 2021-05-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210510_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='username',
        ),
    ]
