# Generated by Django 3.1.7 on 2021-05-10 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('token_seguranca', models.CharField(max_length=30)),
                ('no_uso', models.BooleanField(default=False)),
                ('data_desativacao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('ip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('no_uso', models.BooleanField(default=False)),
                ('codigo_hexa', models.CharField(max_length=30)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_desativacao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(error_messages={'unique': 'Já existe uma pessoa registada com este email!'}, max_length=60, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Gestor_Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('edificio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixas.edificio')),
                ('gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registo', models.DateField(auto_now_add=True)),
                ('data_validação', models.DateField(blank=True, null=True)),
                ('validado', models.BooleanField(default=True)),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixas.caixa')),
                ('cartao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixas.cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa_Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('cartao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixas.cartao')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixas.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=50)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('edificio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixas.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa_Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixas.caixa')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixas.local')),
            ],
        ),
        migrations.AddField(
            model_name='caixa',
            name='local_atual_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caixas.local'),
        ),
    ]
