# Generated by Django 3.1.7 on 2021-05-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registo',
            old_name='data_registo',
            new_name='data_caixa',
        ),
        migrations.RenameField(
            model_name='registo',
            old_name='data_validação',
            new_name='data_servidor',
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='no_uso',
        ),
        migrations.AddField(
            model_name='caixa',
            name='mac_adress',
            field=models.CharField(default='0.0.0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='registo',
            name='codigo_validacao',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='token_seguranca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='codigo_hexa',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Formato: YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Formato: YYYY-MM-DD', null=True),
        ),
    ]
