# Generated by Django 3.1.7 on 2021-06-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
