# Generated by Django 3.1.7 on 2021-06-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0002_auto_20210612_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='data_modificado',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
