# Generated by Django 3.1.7 on 2021-07-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0002_auto_20210713_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='ip_address',
            field=models.CharField(default='000.000.000.000', max_length=50),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='mac_address',
            field=models.CharField(default='00:00:00:00:00:00', error_messages={'unique': 'Já existe uma caixa com este mac_address!'}, max_length=50, unique=True),
        ),
    ]
