# Generated by Django 3.1.7 on 2021-06-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0003_auto_20210612_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='data_modificado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
