# Generated by Django 3.1.7 on 2021-05-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0003_auto_20210524_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rel_gestor_edificio',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
