# Generated by Django 3.1.7 on 2021-05-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0004_auto_20210524_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registo',
            name='data_caixa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registo',
            name='data_servidor',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
