# Generated by Django 3.1.7 on 2021-06-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0005_auto_20210612_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='data_adicionado',
            new_name='data_criacao',
        ),
        migrations.AlterField(
            model_name='caixa',
            name='data_modificado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caixa_local',
            name='data_modificado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caixa_local',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='data_modificado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='data_modificado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='criado_por',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_modificado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa_cartao',
            name='data_modificado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa_cartao',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registo',
            name='data_modificado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registo',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rel_gestor_edificio',
            name='data_modificado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rel_gestor_edificio',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
