# Generated by Django 3.1.7 on 2021-05-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0005_auto_20210527_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='ativo',
        ),
    ]
