# Generated by Django 3.1.7 on 2021-06-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0006_auto_20210614_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=51),
        ),
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
