# Generated by Django 3.1.7 on 2021-06-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0007_auto_20210615_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='no_uso',
        ),
        migrations.AlterField(
            model_name='edificio',
            name='descricao',
            field=models.CharField(blank=True, max_length=51),
        ),
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='descricao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
