# Generated by Django 3.1.7 on 2021-06-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0008_auto_20210615_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='registo',
            name='local_atual_caixa',
            field=models.CharField(blank=True, default='default', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registo',
            name='nome_atual_cartao',
            field=models.CharField(blank=True, default='default', max_length=50, null=True),
        ),
    ]
